from enum import Enum

class UserRole(str, Enum):
    client = "client"
    specialist = "specialist"
    admin = "admin"


class OrderStatus(str, Enum):
    open = "open"
    in_progress = "in_progress"
    completed = "completed"
    cancelled = "cancelled"


class AuditAction(str, Enum):
    USER_REGISTER = "New User Register"
    LOGIN_SUCCESS = "Login Success"
    LOGIN_FAILED = "Login Failed"
    UPDATE_USER = "Update Profile"
    DELETE_USER = "Delete Profile"
    SPECIALIST_CREATED = "Create Specialist"
    GET_SPECIALIST = "Get Specialist"
    SPECIALIST_UPDATED = "Update Specialist"
    SPECIALIST_DEACTIVATED = "Deactivate Specialist"
    SPECIALIST_DELETED = "Delete Specialist"
    SPECIALIST_VERIFIED = "Verify Specialist"
    SPECIALIST_SEARCH = "Search Near Specialist"
    CREATE_ORDER = "Create Order"
    GET_ORDER = "Get Order"
    UPDATE_ORDER = "Update Order"
    DEACTIVATE_ORDER = "Deactivate Order"
    DELETE_ORDER = "Delete Order"
    TAKE_ORDER = "Take Order"
    COMPLETE_ORDER = "Complete Order"
    CANCEL_ORDER = "Cancel Order"
    CREATE_CATALOG_ITEM = "Create Catalog Item"
    GET_CATALOG = "Get Catalog Items"
    GET_SPECIALIST_CATALOG = "Get Specialist Catalog Items"
    UPDATE_CATALOG_ITEM = "Update Catalog Item"
    DELETE_CATALOG_ITEM = "Delete Catalog Item"
    CREATE_ACCREDITATION = "Create Accreditation"
    GET_SPECIALIST_ACCREDITATIONS = "Get Specialist Accreditations"
    DELETE_ACCREDITATION = "Delete Accreditation"
    CREATE_ADDRESS = "Create Address"
    DELETE_ADDRESS = "Delete Address"
    CREATE_COMMENT = "Create Comment"
    GET_SPECIALIST_COMMENTS = "Get Specialist Comments"
    DELETE_COMMENT = "Delete Comment"
    CREATE_RATE = "Create Rate"
    GET_SPECIALIST_RATES = "Get Specialist Rates"
    DELETE_RATE = "Delete Rate"
    CREATE_MESSAGE = "Create Message"
    GET_ORDER_MESSAGES = "Get Order Messages"